import { Link } from 'react-router-dom'
import { Minus, Plus, Trash2, ArrowRight, ShoppingBag } from 'lucide-react'

export default function Cart({items,onUpdate,onRemove}) {
  const subtotal=items.reduce((s,i)=>s+Number(i.price)*(i.quantity||1),0)
  const shipping=subtotal>=1499||subtotal===0?0:99
  const total=subtotal+shipping
  return <main className="section container cart-page"><div className="shop-title"><div><p className="eyebrow">YOUR SELECTION</p><h1>Shopping <em>bag.</em></h1></div><span className="result-count">{items.length} items</span></div>{!items.length?<div className="empty cart-empty"><ShoppingBag size={42}/><h3>Your bag is waiting</h3><p>Find something you love and make it yours.</p><Link className="primary-btn dark" to="/products">Continue shopping <ArrowRight size={17}/></Link></div>:<div className="cart-grid"><div className="cart-items">{items.map((i,index)=><div className="cart-item" key={`${i.id}-${i.selectedSize}-${index}`}><img src={i.image} alt={i.name}/><div className="cart-item-info"><div className="product-meta"><span>{i.category}</span></div><h3>{i.name}</h3><p>Size: {i.selectedSize || i.sizes?.[0] || 'M'}</p><strong>₹{Number(i.price).toLocaleString('en-IN')}</strong><div className="cart-actions"><div className="qty"><button onClick={()=>onUpdate(index,Math.max(1,(i.quantity||1)-1))}><Minus size={14}/></button><span>{i.quantity||1}</span><button onClick={()=>onUpdate(index,(i.quantity||1)+1)}><Plus size={14}/></button></div><button className="remove" onClick={()=>onRemove(index)}><Trash2 size={15}/> Remove</button></div></div></div>)}</div><aside className="summary"><h3>Order summary</h3><div><span>Subtotal</span><strong>₹{subtotal.toLocaleString('en-IN')}</strong></div><div><span>Shipping</span><strong>{shipping?'₹99':'Free'}</strong></div><hr/><div className="total"><span>Total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><button className="primary-btn full">Checkout <ArrowRight size={17}/></button><p className="secure-note">Secure checkout · 7-day returns</p></aside></div>}</main>
}
